<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Optimize>true</Optimize>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <!-- NativeAOT / Trimming compatibility -->
    <PublishAot>false</PublishAot><!-- set true when publishing for AOT verification -->
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>

    <AssemblyName>AeternumDB.PoC.Unsafe</AssemblyName>
    <RootNamespace>AeternumDB.PoC.Unsafe</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\AeternumDB.PoC.Shared.csproj" />
    <PackageReference Include="BenchmarkDotNet" Version="0.*" />
    <PackageReference Include="BenchmarkDotNet.Diagnostics.Windows" Version="0.*" Condition="$([MSBuild]::IsOSPlatform('Windows'))" />
    <PackageReference Include="GenDI" Version="26.*" />
    <PackageReference Include="GenDI.SourceGenerator" Version="26.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>contentfiles; compile; runtime</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.*" />
  </ItemGroup>
</Project>

